In [1]:
import numpy as np
import torch

In [3]:
# Initialize a numpy array and a torch tensor
a = np.array(1)
b = torch.tensor(1)
print("Numpy:{} \nTorch:{}".format(a, b))

Numpy:1 
Torch:1


In [4]:
# type check
print("Numpy Type:{}\nTorch Type:{}".format(type(a), type(b)))

Numpy Type:<class 'numpy.ndarray'>
Torch Type:<class 'torch.Tensor'>


In [8]:
def do_matrix_math(a, b):
    # Addition
    print(a+b)
    # Subtraction
    print(a-b)
    #Multiplication
    print(a*b)
    #Division
    print(a/b)

In [9]:
# Math time
a = np.array(2)
b = np.array(1)
print(a,b)

2 1


In [10]:
do_matrix_math(a,b)

3
1
2
2.0


In [11]:
# Pytroch Mat
a = torch.tensor(2)
b = torch.tensor(1)
print(a,b)

tensor(2) tensor(1)


In [12]:
do_matrix_math(a,b)

tensor(3)
tensor(1)
tensor(2)
tensor(2)


In [13]:
# Matrix time
a = np.zeros((3,3))
print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)


In [14]:
a = torch.zeros((3,3))
print(a)
print(a.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [15]:
#building a neural network, we randomly initialize the weights for the model. So, let’s see how we can initialize a matrix with random numbers:
# random seed
np.random.seed(42)
# Random numbers
a = np.random.randn(3,3)
print(a)

[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]


In [16]:
# Pytorch version
torch.manual_seed(42)
a = torch.randn(3,3)
print(a)

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])


In [18]:
# Matrix Opperations
torch.manual_seed(42)
a = torch.randn(3,3)
b = torch.randn(3,3)
print(torch.add(a,b), '\n')
print(torch.sub(a,b), '\n')
print(torch.mm(a,b), '\n')
print(torch.div(a,b), '\n')

tensor([[ 0.6040,  0.6637,  1.0438],
        [ 1.3406, -2.8127, -1.1753],
        [ 3.1662,  0.6841,  1.2788]]) 

tensor([[ 0.0693, -0.4061, -0.5749],
        [-0.8800,  0.5669,  0.8026],
        [ 1.2502, -1.9601, -0.3555]]) 

tensor([[ 0.4576,  0.2724,  0.3367],
        [-1.3636,  1.7743,  1.1446],
        [ 0.3243,  2.8696,  2.7954]]) 

tensor([[ 1.2594,  0.2408,  0.2897],
        [ 0.2075,  0.6645,  0.1884],
        [ 2.3051, -0.4826,  0.5649]]) 



In [20]:
# Transpose
print(a, '\n')
print(torch.t(a))

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]]) 

tensor([[ 0.3367,  0.2303,  2.2082],
        [ 0.1288, -1.1229, -0.6380],
        [ 0.2345, -0.1863,  0.4617]])


In [21]:
def print_tensors(tensor1, tensor2):
    print(tensor1, ('\n'))
    print(tensor2)

In [25]:
# Concatenating tensors
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
print_tensors(a,b)
print(torch.cat((a,b)))

tensor([[1, 2],
        [3, 4]]) 

tensor([[5, 6],
        [7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [26]:
virtical_concatination = torch.cat((a,b))
horizontal_concatination = torch.cat((a,b), dim=1)
print_tensors(virtical_concatination, horizontal_concatination)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]) 

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [27]:
# Reshaping tensors
a = torch.randn(2,4)
print(a)
print(a.shape)

tensor([[-0.7658, -0.7506,  1.3525,  0.6863],
        [-0.3278,  0.7950,  0.2815,  0.0562]])
torch.Size([2, 4])


In [28]:
b = a.reshape(1,8) # [2,4] = new shape 1, 2*4
print(b)
print(b.shape)

tensor([[-0.7658, -0.7506,  1.3525,  0.6863, -0.3278,  0.7950,  0.2815,  0.0562]])
torch.Size([1, 8])


In [29]:
#Convert numpy to tensor
a = np.array([[1,2],[3,4]])
print(a, '\n')
tensor = torch.from_numpy(a)
print(tensor)

[[1 2]
 [3 4]] 

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [30]:
# Common pytorch modules
# Autograd module
# it recoreds all opperations that are performed and replays it backward to compute gradietns
# Save time per epoch on the forward pass too
# requires_grad=True sets the gradients to be stored for this tensor
a = torch.ones((2,2), requires_grad=True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [31]:
b = a + 5
c = b.mean() # c = mean(b) = Σ(a+5) / 4 (4 is the number of item in the tensor)
print(b, c)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>) tensor(6., grad_fn=<MeanBackward0>)


In [32]:
# Back prop
c.backward()
# Compute the gradients
print(a.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [33]:
# Optim Module
from torch import optim
# adam
## adam = optim.Adam(model.parameters(), lr=learning_rate)
# sgd
## SGD = optim.SGD(model.parameters(), lr=learning_rate)
'''
SGD
Adam
Adadelta
Adagrad
AdamW
SparseAdam
Adamax
ASGD (Averaged Stochastic Gradient Descent)
RMSprop
Rprop (resilient backpropagation)
'''

'\nSGD\nAdam\nAdadelta\nAdagrad\nAdamW\nSparseAdam\nAdamax\nASGD (Averaged Stochastic Gradient Descent)\nRMSprop\nRprop (resilient backpropagation)\n'

In [34]:
# Basic NN in pytorch
# Input tensor
X = torch.tensor([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
# Output
Y = torch.tensor([[1],[1],[0]])
print_tensors(X,Y)

tensor([[1, 0, 1, 0],
        [1, 0, 1, 1],
        [0, 1, 0, 1]]) 

tensor([[1],
        [1],
        [0]])


In [35]:
# Sigmoid function
def sigmoid(x):
    return 1/(1 + torch.exp(-x))

def derivatives_sigmoid(x):
    return x * (1-x)

In [54]:
# Variable initialization
epochs = 500
lr = 0.1 
inputlayer_neurons = X.shape[1] # Gives the number of features in data
hiddenlayer_neurons = 3 # number of hidden layers
output_neurons = 1 # Number of beurons in output layer

# Weights and bias
wh = torch.randn(inputlayer_neurons, hiddenlayer_neurons).type(torch.FloatTensor)
bh = torch.randn(1, hiddenlayer_neurons).type(torch.FloatTensor)
wout = torch.randn(hiddenlayer_neurons, output_neurons)
bout = torch.randn(1, output_neurons)

In [55]:
# Define a single layer input hidden layer and output model
for i in range(epoch):
    #Forward Propogation
    hidden_layer_input1 = torch.mm(X, wh)
    hidden_layer_input = hidden_layer_input1 + bh
    hidden_layer_activations = sigmoid(hidden_layer_input)

    output_layer_input1 = torch.mm(hidden_layer_activations, wout)
    output_layer_input = output_layer_input1 + bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hidden_layer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = torch.mm(d_output, wout.t())
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += torch.mm(hidden_layer_activations.t(), d_output) *lr
    bout += d_output.sum() *lr
    wh += torch.mm(X.t(), d_hiddenlayer) *lr
    bh += d_output.sum() *lr

RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #2 'mat2'